<table border="0">
  <tr>
    <td width="75%">
      <h1>刘国远</h1>
      <p><b>本科生</b></p>
      <p><b>浙江万里学院</b></p>
      <p><b>邮箱：2456868572@qq.com</b></p>
      <p><b>地址：宁波市鄞州区×</b></p>
    </td>
    <td width="25%">
      <img src="微信图片_20200205203820.jpg" width="100%">      
    </td>
  </tr>
</table>
###个人简历
####2017年至2019年在西藏军区昌都军分区某部队服役
###获得奖励
####2019年在西藏军区昌都军分区某部队获嘉奖
####2019年十月参加校运会在5000米与10000米中均获得第一名
###兴趣爱好
####跑步
theme: jekyll-theme-cayman
